### ISSUE TITLE
API document written in README.md is dead link

### ISSUE THREAD

**Issue by pankona** [kachick/ruby-ulid#68]
It seems README shows a link to the API documentation but it is a dead link now.
https://rubydoc.info/github/kachick/ruby-ulid/

**Comment by pankona** [comment]
Sorry, it was not the problem. It is outdated link and currently it works with this link https://kachick.github.io/ruby-ulid/

**Comment by kachick** [comment]
Yes! I automated the self-hosted documentation since below issues!

https://github.com/kachick/ruby-ulid/issues/27
https://github.com/kachick/ruby-ulid/issues/28
