### ISSUE TITLE
Yank some old released versions from https://rubygems.org/ because included unexpected `console` command

### ISSUE THREAD

**Issue by kachick** [kachick/ruby-ulid#69]
1. Included `bin/console` as `executable command` in my mistaken 🙇  
1. Minimized since cece523f7325c7c8529364cf1cd8876530405776
1. Includes some files again with strict checker since 689b8948e7f5d3f065960796756ac02dcf9ec0f8

Basically `yank` is a bad for users, I think.
But 

>Included `bin/console` as `executable command`

Is a crucial bug, so should be yanked!

The target versions are before of https://github.com/kachick/ruby-ulid/releases/tag/v0.0.6

<img width="369" alt="スクリーンショット 2021-05-03 11 54 56" src="https://user-images.githubusercontent.com/1180335/116837677-6c331380-ac06-11eb-95c9-fd9c064924e8.png">

**Comment by kachick** [comment]
<img width="614" alt="スクリーンショット 2021-05-03 12 00 11" src="https://user-images.githubusercontent.com/1180335/116837898-32aed800-ac07-11eb-86b1-0ad3133d0e4b.png">

☺️ 🙇 

cc: @pankona

**Comment by pankona** [comment]
Good!

**Comment by kachick** [comment]
https://blog.rubygems.org/2015/04/13/permadelete-on-yank.html 👀
